---@class ModReference
local mod = DiesIraeMod

mod.Pools ={
    -------------------------------------
    ---         TRANSFORMATIONS
    -------------------------------------
    DadPlaylistItem = {
        mod.Items.TheBadTouch,
        mod.Items.ArmyOfLovers,
        mod.Items.LittleLies,
        mod.Items.ShBoom,
        mod.Items.Universal,
        mod.Items.EverybodysChanging,
        mod.Items.U2,
        mod.Items.KillerQueen,
        mod.Items.RingOfFire,
        mod.Items.HelterSkelter,
        mod.Items.Muse
    },
    SinfulMusicItem = {
        mod.Items.HereToStay,
        mod.Items.Hysteria,
        mod.Items.Mutter,
        mod.Items.LastResort,
        mod.Items.HypaHypa,
        mod.Items.HolyWood,
        mod.Items.DiaryOfAMadman,
        mod.Items.ComaWhite,
        mod.Items.KoRn,
        mod.Items.Psychosocial,
        mod.Items.SymphonyOfDestr,
        CollectibleType.COLLECTIBLE_DUALITY,
        CollectibleType.COLLECTIBLE_SULFUR
    },
    Relics ={
        CollectibleType.COLLECTIBLE_BLOOD_OF_THE_MARTYR,
        CollectibleType.COLLECTIBLE_DEAD_SEA_SCROLLS,
        CollectibleType.COLLECTIBLE_HOLY_GRAIL,
        CollectibleType.COLLECTIBLE_BOOK_OF_REVELATIONS,
        CollectibleType.COLLECTIBLE_HOLY_WATER,
        CollectibleType.COLLECTIBLE_BIBLE,
        CollectibleType.COLLECTIBLE_CELTIC_CROSS,
        CollectibleType.COLLECTIBLE_MITRE,
        CollectibleType.COLLECTIBLE_RELIC,
        CollectibleType.COLLECTIBLE_HOLY_MANTLE
    },
    -------------------------------------
    ---             BEGGARS
    -------------------------------------
    Tech = {
        CollectibleType.COLLECTIBLE_TECHNOLOGY,
        CollectibleType.COLLECTIBLE_TECH_X,
        CollectibleType.COLLECTIBLE_TECHNOLOGY_2,
        CollectibleType.COLLECTIBLE_TRACTOR_BEAM,
        CollectibleType.COLLECTIBLE_TECHNOLOGY_ZERO,
        CollectibleType.COLLECTIBLE_LUDOVICO_TECHNIQUE,
        CollectibleType.COLLECTIBLE_ROBO_BABY,
        CollectibleType.COLLECTIBLE_ROBO_BABY_2,
        CollectibleType.COLLECTIBLE_TECH_5,
        CollectibleType.COLLECTIBLE_SPIDER_MOD,
        CollectibleType.COLLECTIBLE_JACOBS_LADDER,
        CollectibleType.COLLECTIBLE_120_VOLT,
        CollectibleType.COLLECTIBLE_BOT_FLY
    },
    Guppy = {
        CollectibleType.COLLECTIBLE_GUPPYS_EYE,
        CollectibleType.COLLECTIBLE_GUPPYS_PAW,
        CollectibleType.COLLECTIBLE_GUPPYS_TAIL,
        CollectibleType.COLLECTIBLE_GUPPYS_HEAD,
        CollectibleType.COLLECTIBLE_GUPPYS_HAIRBALL,
        CollectibleType.COLLECTIBLE_GUPPYS_COLLAR,
        mod.Items.GuppysSoul,
    },
    Doctor = {
        CollectibleType.COLLECTIBLE_VIRUS,
        CollectibleType.COLLECTIBLE_ROID_RAGE,
        CollectibleType.COLLECTIBLE_GROWTH_HORMONES,
        CollectibleType.COLLECTIBLE_SPEED_BALL,
        CollectibleType.COLLECTIBLE_EXPERIMENTAL_TREATMENT,
        CollectibleType.COLLECTIBLE_SYNTHOIL,
        CollectibleType.COLLECTIBLE_ADRENALINE,
        CollectibleType.COLLECTIBLE_EUTHANASIA,
        CollectibleType.COLLECTIBLE_FALSE_PHD,
        CollectibleType.COLLECTIBLE_PHD,
        CollectibleType.COLLECTIBLE_SUPER_BANDAGE,
        CollectibleType.COLLECTIBLE_MOMS_BOTTLE_OF_PILLS,
        CollectibleType.COLLECTIBLE_IV_BAG,
        CollectibleType.COLLECTIBLE_BLOOD_BAG,
        CollectibleType.COLLECTIBLE_OLD_BANDAGE,
        CollectibleType.COLLECTIBLE_E_COLI,
        CollectibleType.COLLECTIBLE_CAFFEINE_PILL,
    },
    LostAdventurer = {
        CollectibleType.COLLECTIBLE_COMPASS,
        CollectibleType.COLLECTIBLE_BOOK_OF_SECRETS,
        CollectibleType.COLLECTIBLE_BLUE_MAP,
        CollectibleType.COLLECTIBLE_TREASURE_MAP,
        mod.Items.UltraSecretMap,
        mod.Items.DevilsMap,
        mod.Items.BossCompass
    },
    Familiar_Beggar_Trinkets = {
        TrinketType.TRINKET_UMBILICAL_CORD,
        TrinketType.TRINKET_ISAACS_HEAD,
        TrinketType.TRINKET_SOUL,
        TrinketType.TRINKET_EVES_BIRD_FOOT,
        TrinketType.TRINKET_CHILD_LEASH,
        TrinketType.TRINKET_DUCT_TAPE,
        TrinketType.TRINKET_EXTENSION_CORD,
        TrinketType.TRINKET_BABY_BENDER,
        TrinketType.TRINKET_FORGOTTEN_LULLABY,
        TrinketType.TRINKET_FRIENDSHIP_NECKLACE,
        TrinketType.TRINKET_RC_REMOTE,
        TrinketType.TRINKET_FOUND_SOUL,
        TrinketType.TRINKET_THE_TWINS,
    },
    Familiar_Beggar_Items = {
        ---Familiars related items
        CollectibleType.COLLECTIBLE_MONSTER_MANUAL,
        CollectibleType.COLLECTIBLE_BFFS,
        CollectibleType.COLLECTIBLE_BOX_OF_FRIENDS,
        CollectibleType.COLLECTIBLE_CAMBION_CONCEPTION,
        CollectibleType.COLLECTIBLE_IMMACULATE_CONCEPTION,
        CollectibleType.COLLECTIBLE_SCOOPER,
    },
    -------------------------------------
    ---             MINIBOSSES
    -------------------------------------
    Uncertantity = {
        CollectibleType.COLLECTIBLE_D_INFINITY,
        CollectibleType.COLLECTIBLE_LIL_DELIRIUM,
        CollectibleType.COLLECTIBLE_DELIRIOUS,
    },
    -------------------------------------
    ---             EXTRA
    -------------------------------------
    curseList = {
        LevelCurse.CURSE_OF_DARKNESS,
        LevelCurse.CURSE_OF_LABYRINTH,
        LevelCurse.CURSE_OF_THE_LOST,
        LevelCurse.CURSE_OF_THE_UNKNOWN,
        LevelCurse.CURSE_OF_BLIND,
        LevelCurse.CURSE_OF_MAZE
    },
    TarotCards = {
        Card.CARD_FOOL,
        Card.CARD_MAGICIAN,
        Card.CARD_HIGH_PRIESTESS,
        Card.CARD_EMPRESS,
        Card.CARD_EMPEROR,
        Card.CARD_HIEROPHANT,
        Card.CARD_LOVERS,
        Card.CARD_CHARIOT,
        Card.CARD_JUSTICE,
        Card.CARD_HERMIT,
        Card.CARD_WHEEL_OF_FORTUNE,
        Card.CARD_STRENGTH,
        Card.CARD_HANGED_MAN,
        Card.CARD_DEATH,
        Card.CARD_TEMPERANCE,
        Card.CARD_DEVIL,
        Card.CARD_TOWER,
        Card.CARD_STARS,
        Card.CARD_MOON,
        Card.CARD_SUN,
        Card.CARD_JUDGEMENT,
        Card.CARD_WORLD
    },
    ReverseCards = {
        Card.CARD_REVERSE_FOOL,
        Card.CARD_REVERSE_MAGICIAN,
        Card.CARD_REVERSE_HIGH_PRIESTESS,
        Card.CARD_REVERSE_EMPRESS,
        Card.CARD_REVERSE_EMPEROR,
        Card.CARD_REVERSE_HIEROPHANT,
        Card.CARD_REVERSE_LOVERS,
        Card.CARD_REVERSE_CHARIOT,
        Card.CARD_REVERSE_JUSTICE,
        Card.CARD_REVERSE_HERMIT,
        Card.CARD_REVERSE_WHEEL_OF_FORTUNE,
        Card.CARD_REVERSE_STRENGTH,
        Card.CARD_REVERSE_HANGED_MAN,
        Card.CARD_REVERSE_DEATH,
        Card.CARD_REVERSE_TEMPERANCE,
        Card.CARD_REVERSE_DEVIL,
        Card.CARD_REVERSE_TOWER,
        Card.CARD_REVERSE_STARS,
        Card.CARD_REVERSE_MOON,
        Card.CARD_REVERSE_SUN,
        Card.CARD_REVERSE_JUDGEMENT,
        Card.CARD_REVERSE_WORLD
    },
    RuneOrSoul = {
        [Card.RUNE_HAGALAZ]  = true,
        [Card.RUNE_JERA]     = true,
        [Card.RUNE_EHWAZ]    = true,
        [Card.RUNE_DAGAZ]    = true,
        [Card.RUNE_ANSUZ]    = true,
        [Card.RUNE_PERTHRO]  = true,
        [Card.RUNE_BERKANO]  = true,
        [Card.RUNE_ALGIZ]    = true,
        [Card.RUNE_BLACK]    = true,
        [Card.CARD_SOUL_ISAAC]       = true,
        [Card.CARD_SOUL_MAGDALENE]   = true,
        [Card.CARD_SOUL_CAIN]        = true,
        [Card.CARD_SOUL_JUDAS]       = true,
        [Card.CARD_SOUL_BLUEBABY]    = true,
        [Card.CARD_SOUL_EVE]         = true,
        [Card.CARD_SOUL_SAMSON]      = true,
        [Card.CARD_SOUL_AZAZEL]      = true,
        [Card.CARD_SOUL_LAZARUS]     = true,
        [Card.CARD_SOUL_EDEN]        = true,
        [Card.CARD_SOUL_LOST]        = true,
        [Card.CARD_SOUL_LILITH]      = true,
        [Card.CARD_SOUL_KEEPER]      = true,
        [Card.CARD_SOUL_APOLLYON]    = true,
        [Card.CARD_SOUL_FORGOTTEN]   = true,
        [Card.CARD_SOUL_BETHANY]     = true,
        [Card.CARD_SOUL_JACOB]       = true,
    },
    GoodPills ={
        PillEffect.PILLEFFECT_BALLS_OF_STEEL,
        PillEffect.PILLEFFECT_FULL_HEALTH,
        PillEffect.PILLEFFECT_HEALTH_UP,
        PillEffect.PILLEFFECT_PRETTY_FLY,
        PillEffect.PILLEFFECT_RANGE_UP,
        PillEffect.PILLEFFECT_SPEED_UP,
        PillEffect.PILLEFFECT_TEARS_UP,
        PillEffect.PILLEFFECT_LUCK_UP,
        PillEffect.PILLEFFECT_48HOUR_ENERGY,
        PillEffect.PILLEFFECT_SEE_FOREVER,
        PillEffect.PILLEFFECT_PHEROMONES,
        PillEffect.PILLEFFECT_LEMON_PARTY,
        PillEffect.PILLEFFECT_PERCS,
        PillEffect.PILLEFFECT_INFESTED_EXCLAMATION,
        PillEffect.PILLEFFECT_INFESTED_QUESTION,
        PillEffect.PILLEFFECT_POWER,
        PillEffect.PILLEFFECT_FRIENDS_TILL_THE_END,
        PillEffect.PILLEFFECT_GULP,
        PillEffect.PILLEFFECT_VURP,
        PillEffect.PILLEFFECT_SUNSHINE,
        PillEffect.PILLEFFECT_SHOT_SPEED_UP,
        mod.Pills.VOMIT
    },
    BadPills ={
        PillEffect.PILLEFFECT_BAD_TRIP,
        PillEffect.PILLEFFECT_HEALTH_DOWN,
        PillEffect.PILLEFFECT_RANGE_DOWN,
        PillEffect.PILLEFFECT_SPEED_DOWN,
        PillEffect.PILLEFFECT_TEARS_DOWN,
        PillEffect.PILLEFFECT_LUCK_DOWN,
        PillEffect.PILLEFFECT_PARALYSIS,
        PillEffect.PILLEFFECT_AMNESIA,
        PillEffect.PILLEFFECT_WIZARD,
        PillEffect.PILLEFFECT_ADDICTED,
        PillEffect.PILLEFFECT_QUESTIONMARK,
        PillEffect.PILLEFFECT_RETRO_VISION,
        PillEffect.PILLEFFECT_SHOT_SPEED_DOWN,
        mod.Pills.CURSED,
        mod.Pills.HEARTBREAK,
        mod.Pills.POWER_DRAIN,
    },
    Red_Trinkets= {
        TrinketType.TRINKET_PERFECTION,
        TrinketType.TRINKET_APOLLYONS_BEST_FRIEND,
        TrinketType.TRINKET_NUH_UH,
        TrinketType.TRINKET_PANIC_BUTTON,
        TrinketType.TRINKET_RING_CAP,
        TrinketType.TRINKET_KEEPERS_BARGAIN,
        TrinketType.TRINKET_SWALLOWED_M80,
        TrinketType.TRINKET_LIL_CLOT,
        TrinketType.TRINKET_MOTHERS_KISS,
        TrinketType.TRINKET_WICKED_CROWN,
        TrinketType.TRINKET_BROKEN_SYRINGE,
        TrinketType.TRINKET_NUMBER_MAGNET,
        TrinketType.TRINKET_FRIENDSHIP_NECKLACE,
        TrinketType.TRINKET_SHORT_FUSE,
        TrinketType.TRINKET_TEMPORARY_TATTOO,
        TrinketType.TRINKET_BROKEN_MAGNET,
        TrinketType.TRINKET_BLOODY_PENNY,
        TrinketType.TRINKET_ROSARY_BEAD,
        TrinketType.TRINKET_CHILDS_HEART,
        TrinketType.TRINKET_JUDAS_TONGUE,
        TrinketType.TRINKET_RED_PATCH,
        TrinketType.TRINKET_POKER_CHIP,
        TrinketType.TRINKET_SECOND_HAND,
        TrinketType.TRINKET_BLASTING_CAP,
        TrinketType.TRINKET_ERROR,
        TrinketType.TRINKET_MOMS_LOCKET,
        TrinketType.TRINKET_LOCUST_OF_WRATH,
        TrinketType.TRINKET_EQUALITY,
        TrinketType.TRINKET_BLOODY_CROWN,
        TrinketType.TRINKET_STEM_CELL
    },
    -------------------------------------
    ---          ELIJAH Pools
    -------------------------------------
    Elijah_blacklist = {
        CollectibleType.COLLECTIBLE_DOLLAR,
        CollectibleType.COLLECTIBLE_QUARTER,
        CollectibleType.COLLECTIBLE_SACK_OF_PENNIES,
        CollectibleType.COLLECTIBLE_PAGEANT_BOY,
        CollectibleType.COLLECTIBLE_BUM_FRIEND,
        CollectibleType.COLLECTIBLE_PORTABLE_SLOT,
        CollectibleType.COLLECTIBLE_PIGGY_BANK,
        CollectibleType.COLLECTIBLE_MYSTERY_SACK,
        CollectibleType.COLLECTIBLE_BLUE_BOX,
        CollectibleType.COLLECTIBLE_WOODEN_NICKEL,
        CollectibleType.COLLECTIBLE_BUMBO,
        CollectibleType.COLLECTIBLE_SACK_HEAD,
        CollectibleType.COLLECTIBLE_HEAD_OF_THE_KEEPER,
        CollectibleType.COLLECTIBLE_EYE_OF_GREED,
        CollectibleType.COLLECTIBLE_DADS_LOST_COIN,
        CollectibleType.COLLECTIBLE_GREEDS_GULLET,
        CollectibleType.COLLECTIBLE_GOLDEN_RAZOR,
        CollectibleType.COLLECTIBLE_KEEPERS_SACK,
        CollectibleType.COLLECTIBLE_POUND_OF_FLESH,
        CollectibleType.COLLECTIBLE_COUPON,
        CollectibleType.COLLECTIBLE_DEEP_POCKETS,
        CollectibleType.COLLECTIBLE_PAY_TO_PLAY,
        mod.Items.ScammerBum,
        mod.Items.FilthyRich,
    },
    Slot_blacklist = {
        SlotVariant.SLOT_MACHINE,
        SlotVariant.FORTUNE_TELLING_MACHINE,
        SlotVariant.CRANE_GAME,
        SlotVariant.CONFESSIONAL,
        SlotVariant.HELL_GAME,
    },
    Trinket_blacklist = {
        TrinketType.TRINKET_SWALLOWED_PENNY,
        TrinketType.TRINKET_BUTT_PENNY,
        TrinketType.TRINKET_BLOODY_PENNY,
        TrinketType.TRINKET_BURNT_PENNY,
        TrinketType.TRINKET_FLAT_PENNY,
        TrinketType.TRINKET_COUNTERFEIT_PENNY,
        TrinketType.TRINKET_ROTTEN_PENNY,
        TrinketType.TRINKET_BLESSED_PENNY,
        TrinketType.TRINKET_CHARGED_PENNY,
        TrinketType.TRINKET_CURSED_PENNY,
        TrinketType.TRINKET_STORE_CREDIT,
        TrinketType.TRINKET_KEEPERS_BARGAIN
    },
    CHAOS_ELIJAH_BEGGARS = {
        mod.Entities.BEGGAR_TreasureElijah.Var,
        mod.Entities.BEGGAR_ShopElijah.Var,
        mod.Entities.BEGGAR_DemonElijah.Var,
        mod.Entities.BEGGAR_AngelElijah.Var,
        mod.Entities.BEGGAR_SecretElijah.Var,
        mod.Entities.BEGGAR_UltraSecretElijah.Var,
        mod.Entities.BEGGAR_PlanetariumElijah.Var,
        mod.Entities.BEGGAR_LibraryElijah.Var,
        mod.Entities.BEGGAR_ERROR_Elijah.Var,
        mod.Entities.BEGGAR_Elijah.Var,
        mod.Entities.BEGGAR_BombElijah.Var,
        mod.Entities.BEGGAR_KeyElijah.Var,
        mod.Entities.BEGGAR_RottenElijah.Var,
        mod.Entities.BEGGAR_BatteryElijah.Var,
    },
    ALL_ELIJAH_BEGGARS = {
        --This is for Coupon synergy
        --Not including JYS, Mom's box because of their size 
        --Not including Fiend beggar because he's special
        mod.Entities.BEGGAR_TreasureElijah.Var,
        mod.Entities.BEGGAR_ShopElijah.Var,
        mod.Entities.BEGGAR_DemonElijah.Var,
        mod.Entities.BEGGAR_AngelElijah.Var,
        mod.Entities.BEGGAR_SecretElijah.Var,
        mod.Entities.BEGGAR_UltraSecretElijah.Var,
        mod.Entities.BEGGAR_PlanetariumElijah.Var,
        mod.Entities.BEGGAR_LibraryElijah.Var,
        mod.Entities.BEGGAR_ERROR_Elijah.Var,
        mod.Entities.BEGGAR_Elijah.Var,
        mod.Entities.BEGGAR_BombElijah.Var,
        mod.Entities.BEGGAR_KeyElijah.Var,
        mod.Entities.BEGGAR_Goldsmith_Elijah.Var,
        mod.Entities.BEGGAR_Familiars_Elijah.Var,
        mod.Entities.BEGGAR_Lost_Adventurer_E.Var,
        mod.Entities.BEGGAR_Chaos_Elijah.Var,
        mod.Entities.BEGGAR_Guppy.Var,
        mod.Entities.BEGGAR_SacrificeTable.Var,
        SlotVariant.DEVIL_BEGGAR,
    },
}