---@class ModReference
local mod = DiesIraeMod

mod.Pools ={
    DadPlaylistItem = {
        mod.Items.TheBadTouch,
        mod.Items.ArmyOfLovers,
        mod.Items.LittleLies,
        mod.Items.ShBoom,
        mod.Items.Universal,
        mod.Items.EverybodysChanging,
        mod.Items.U2,
        mod.Items.KillerQueen,
        mod.Items.RingOfFire,
        mod.Items.HelterSkelter,
        mod.Items.Muse
    },
    SinfulMusicItem = {
        mod.Items.HereToStay,
        mod.Items.Hysteria,
        mod.Items.Mutter,
        mod.Items.LastResort,
        mod.Items.HypaHypa,
        mod.Items.HolyWood,
        mod.Items.DiaryOfAMadman,
        mod.Items.ComaWhite,
        mod.Items.KoRn,
        mod.Items.Psychosocial,
        mod.Items.SymphonyOfDestr,
        CollectibleType.COLLECTIBLE_DUALITY,
        CollectibleType.COLLECTIBLE_SULFUR
    },
    Relics ={
        CollectibleType.COLLECTIBLE_BLOOD_OF_THE_MARTYR,
        CollectibleType.COLLECTIBLE_DEAD_SEA_SCROLLS,
        CollectibleType.COLLECTIBLE_HOLY_GRAIL,
        CollectibleType.COLLECTIBLE_BOOK_OF_REVELATIONS,
        CollectibleType.COLLECTIBLE_HOLY_WATER,
        CollectibleType.COLLECTIBLE_BIBLE,
        CollectibleType.COLLECTIBLE_CELTIC_CROSS,
        CollectibleType.COLLECTIBLE_MITRE,
        CollectibleType.COLLECTIBLE_RELIC,
        CollectibleType.COLLECTIBLE_HOLY_MANTLE
    },
    Tech = {
        CollectibleType.COLLECTIBLE_TECHNOLOGY,
        CollectibleType.COLLECTIBLE_TECH_X,
        CollectibleType.COLLECTIBLE_TECHNOLOGY_2,
        CollectibleType.COLLECTIBLE_TRACTOR_BEAM,
        CollectibleType.COLLECTIBLE_TECHNOLOGY_ZERO,
        CollectibleType.COLLECTIBLE_LUDOVICO_TECHNIQUE,
        CollectibleType.COLLECTIBLE_ROBO_BABY,
        CollectibleType.COLLECTIBLE_ROBO_BABY_2,
        CollectibleType.COLLECTIBLE_TECH_5,
        CollectibleType.COLLECTIBLE_SPIDER_MOD,
        CollectibleType.COLLECTIBLE_JACOBS_LADDER,
        CollectibleType.COLLECTIBLE_120_VOLT,
        CollectibleType.COLLECTIBLE_BOT_FLY
    },
    Guppy = {
        CollectibleType.COLLECTIBLE_GUPPYS_EYE,
        CollectibleType.COLLECTIBLE_GUPPYS_PAW,
        CollectibleType.COLLECTIBLE_GUPPYS_TAIL,
        CollectibleType.COLLECTIBLE_GUPPYS_HEAD,
        CollectibleType.COLLECTIBLE_GUPPYS_HAIRBALL,
        CollectibleType.COLLECTIBLE_GUPPYS_COLLAR,
        mod.Items.GuppysSoul,
    },
    Doctor = {
        CollectibleType.COLLECTIBLE_VIRUS,
        CollectibleType.COLLECTIBLE_ROID_RAGE,
        CollectibleType.COLLECTIBLE_GROWTH_HORMONES,
        CollectibleType.COLLECTIBLE_SPEED_BALL,
        CollectibleType.COLLECTIBLE_EXPERIMENTAL_TREATMENT,
        CollectibleType.COLLECTIBLE_SYNTHOIL,
        CollectibleType.COLLECTIBLE_ADRENALINE,
        CollectibleType.COLLECTIBLE_EUTHANASIA,
        CollectibleType.COLLECTIBLE_FALSE_PHD,
        CollectibleType.COLLECTIBLE_PHD,
        CollectibleType.COLLECTIBLE_SUPER_BANDAGE,
        CollectibleType.COLLECTIBLE_MOMS_BOTTLE_OF_PILLS,
        CollectibleType.COLLECTIBLE_IV_BAG,
        CollectibleType.COLLECTIBLE_BLOOD_BAG,
        CollectibleType.COLLECTIBLE_OLD_BANDAGE,
        CollectibleType.COLLECTIBLE_E_COLI,
        CollectibleType.COLLECTIBLE_CAFFEINE_PILL,
    },
    Uncertantity = {
        CollectibleType.COLLECTIBLE_D_INFINITY,
        CollectibleType.COLLECTIBLE_LIL_DELIRIUM,
        CollectibleType.COLLECTIBLE_DELIRIOUS,
    },
    LostAdventurer = {
        CollectibleType.COLLECTIBLE_COMPASS,
        CollectibleType.COLLECTIBLE_BOOK_OF_SECRETS,
        CollectibleType.COLLECTIBLE_BLUE_MAP,
        CollectibleType.COLLECTIBLE_TREASURE_MAP,
        mod.Items.UltraSecretMap,
        mod.Items.DevilsMap,
        mod.Items.BossCompass
    },
    curseList = {
        LevelCurse.CURSE_OF_DARKNESS,
        LevelCurse.CURSE_OF_LABYRINTH,
        LevelCurse.CURSE_OF_THE_LOST,
        LevelCurse.CURSE_OF_THE_UNKNOWN,
        LevelCurse.CURSE_OF_BLIND,
        LevelCurse.CURSE_OF_MAZE
    },

    TarotCards = {
        Card.CARD_FOOL,
        Card.CARD_MAGICIAN,
        Card.CARD_HIGH_PRIESTESS,
        Card.CARD_EMPRESS,
        Card.CARD_EMPEROR,
        Card.CARD_HIEROPHANT,
        Card.CARD_LOVERS,
        Card.CARD_CHARIOT,
        Card.CARD_JUSTICE,
        Card.CARD_HERMIT,
        Card.CARD_WHEEL_OF_FORTUNE,
        Card.CARD_STRENGTH,
        Card.CARD_HANGED_MAN,
        Card.CARD_DEATH,
        Card.CARD_TEMPERANCE,
        Card.CARD_DEVIL,
        Card.CARD_TOWER,
        Card.CARD_STARS,
        Card.CARD_MOON,
        Card.CARD_SUN,
        Card.CARD_JUDGEMENT,
        Card.CARD_WORLD
    },
    ReverseCards = {
        Card.CARD_REVERSE_FOOL,
        Card.CARD_REVERSE_MAGICIAN,
        Card.CARD_REVERSE_HIGH_PRIESTESS,
        Card.CARD_REVERSE_EMPRESS,
        Card.CARD_REVERSE_EMPEROR,
        Card.CARD_REVERSE_HIEROPHANT,
        Card.CARD_REVERSE_LOVERS,
        Card.CARD_REVERSE_CHARIOT,
        Card.CARD_REVERSE_JUSTICE,
        Card.CARD_REVERSE_HERMIT,
        Card.CARD_REVERSE_WHEEL_OF_FORTUNE,
        Card.CARD_REVERSE_STRENGTH,
        Card.CARD_REVERSE_HANGED_MAN,
        Card.CARD_REVERSE_DEATH,
        Card.CARD_REVERSE_TEMPERANCE,
        Card.CARD_REVERSE_DEVIL,
        Card.CARD_REVERSE_TOWER,
        Card.CARD_REVERSE_STARS,
        Card.CARD_REVERSE_MOON,
        Card.CARD_REVERSE_SUN,
        Card.CARD_REVERSE_JUDGEMENT,
        Card.CARD_REVERSE_WORLD
    },

    Elijah_blacklist = {
        CollectibleType.COLLECTIBLE_DOLLAR,
        CollectibleType.COLLECTIBLE_QUARTER,
        CollectibleType.COLLECTIBLE_SACK_OF_PENNIES,
        CollectibleType.COLLECTIBLE_PAGEANT_BOY,
        CollectibleType.COLLECTIBLE_BUM_FRIEND,
        CollectibleType.COLLECTIBLE_PORTABLE_SLOT,
        CollectibleType.COLLECTIBLE_PIGGY_BANK,
        CollectibleType.COLLECTIBLE_MYSTERY_SACK,
        CollectibleType.COLLECTIBLE_BLUE_BOX,
        CollectibleType.COLLECTIBLE_WOODEN_NICKEL,
        CollectibleType.COLLECTIBLE_RESTOCK,
        CollectibleType.COLLECTIBLE_BUMBO,
        CollectibleType.COLLECTIBLE_SACK_HEAD,
        CollectibleType.COLLECTIBLE_HEAD_OF_THE_KEEPER,
        CollectibleType.COLLECTIBLE_EYE_OF_GREED,
        CollectibleType.COLLECTIBLE_DADS_LOST_COIN,
        CollectibleType.COLLECTIBLE_GREEDS_GULLET,
        CollectibleType.COLLECTIBLE_GOLDEN_RAZOR,
        CollectibleType.COLLECTIBLE_KEEPERS_SACK,
    }
}